### ISSUE TITLE
local run fails if branch is not pushed yet

### ISSUE THREAD

**Issue by alexkli** [adobe/sizewatcher#26]
To reproduce:
1. `git co -b custom-comparator`
2. `sizewatcher`

Error:

```
Cloning git repository...
  sizewatcher cloning branches main (before) and custom-comparator (after)... +0ms
  sizewatcher temporary directory: /var/folders/36/3hc24lb17rlb3rj954c7jrbm0000gn/T/tmp-26976-NNnjVJcoKDXB +2ms
  sizewatcher cloning https://github.com/adobe/sizewatcher.git into /var/folders/36/3hc24lb17rlb3rj954c7jrbm0000gn/T/tmp-26976-NNnjVJcoKDXB/before +9ms
  sizewatcher checking out 'main'... +689ms
  sizewatcher cloning https://github.com/adobe/sizewatcher.git into /var/folders/36/3hc24lb17rlb3rj954c7jrbm0000gn/T/tmp-26976-NNnjVJcoKDXB/after +25ms
  sizewatcher checking out 'custom-comparator'... +685ms
GitError: error: pathspec 'custom-comparator' did not match any file(s) known to git

    at GitExecutor.<anonymous> (/Users/alex/Work/code/nui/sizewatcher/node_modules/simple-git/src/lib/git-executor.js:35:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/alex/Work/code/nui/sizewatcher/node_modules/simple-git/src/lib/git-executor.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  task: {
    concatStdErr: false,
    onError: undefined,
    format: 'utf-8',
    commands: [ 'checkout', 'custom-comparator' ],
    parser: [Function: parser]
  }
}
```

**Comment by alexkli** [comment]
Detect remote tracking branch using

```
git rev-parse --abbrev-ref --symbolic-full-name @{u}
```

Will fail with non-zero exit code if not found.

See https://stackoverflow.com/questions/171550/find-out-which-remote-branch-a-local-branch-is-tracking
